[package]
name = "ls-pretty"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.24"
crossterm = "0.27"
clap = { version = "4.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
unicode-width = "0.1"
dirs = "5.0"
